# Generated by Django 4.0.1 on 2022-02-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='zodiac',
            old_name='names',
            new_name='name',
        ),
        migrations.AlterField(
            model_name='zodiac',
            name='information',
            field=models.TextField(max_length=5000),
        ),
    ]
