# Generated by Django 4.0.1 on 2022-02-07 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('horoscope', '0003_person'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Person',
        ),
    ]
